---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strata-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - strata.ctx.sh
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strata.ctx.sh
  resources:
  - collectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - strata.ctx.sh
  resources:
  - discoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - strata.ctx.sh
  resources:
  - discoveries/status
  verbs:
  - get
  - patch
  - update
