apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strata-collector
  namespace: strata-collector
subjects:
  - kind: ServiceAccount
    name: strata-collector
    namespace: strata-collector
roleRef:
  kind: ClusterRole
  name: strata-collector-role
  apiGroup: rbac.authorization.k8s.io
