apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strata-collector
# TODO: add annotations
resources:
  - crd/strata.ctx.sh_collectors.yaml
  - namespace.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - service.yaml
  - deployment.yaml
 
