apiVersion: v1
kind: Service
metadata:
  labels:
    app: collector
  name: strata-ctx-sh-webhook
  namespace: strata-collector
spec:
  type: NodePort
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
      nodePort: 30100
  selector:
    name: collector

