---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-strata-ctx-sh-v1beta1-collector
  failurePolicy: Fail
  name: mcollector.strata.ctx.sh
  rules:
  - apiGroups:
    - strata.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-strata-ctx-sh-v1beta1-discovery
  failurePolicy: Fail
  name: mdiscovery.strata.ctx.sh
  rules:
  - apiGroups:
    - strata.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - discoveries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-strata-ctx-sh-v1beta1-collector
  failurePolicy: Fail
  name: vcollector.strata.ctx.sh
  rules:
  - apiGroups:
    - strata.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-strata-ctx-sh-v1beta1-discovery
  failurePolicy: Fail
  name: vdiscovery.strata.ctx.sh
  rules:
  - apiGroups:
    - strata.ctx.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - discoveries
  sideEffects: None
