/*
 * Copyright 2023 Rob Lyon <rob@ctxswitch.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	stratactxshv1beta1 "ctx.sh/strata-collector/pkg/apis/strata.ctx.sh/v1beta1"
	versioned "ctx.sh/strata-collector/pkg/client/clientset/versioned"
	internalinterfaces "ctx.sh/strata-collector/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "ctx.sh/strata-collector/pkg/client/listers/strata.ctx.sh/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CollectorInformer provides access to a shared informer and lister for
// Collectors.
type CollectorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.CollectorLister
}

type collectorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCollectorInformer constructs a new informer for Collector type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCollectorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCollectorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCollectorInformer constructs a new informer for Collector type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCollectorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StrataV1beta1().Collectors(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StrataV1beta1().Collectors(namespace).Watch(context.TODO(), options)
			},
		},
		&stratactxshv1beta1.Collector{},
		resyncPeriod,
		indexers,
	)
}

func (f *collectorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCollectorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *collectorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&stratactxshv1beta1.Collector{}, f.defaultInformer)
}

func (f *collectorInformer) Lister() v1beta1.CollectorLister {
	return v1beta1.NewCollectorLister(f.Informer().GetIndexer())
}
