apiVersion: strata.ctx.sh/v1beta1
kind: Discovery
metadata:
  name: example
  namespace: default
spec:
  # selector:
  #   matchLabels:
  #     app: example
  collector:
    - name: example
      namespace: default
---
apiVersion: strata.ctx.sh/v1beta1
kind: Collector
metadata:
  name: example
  namespace: default
  labels:
    sink: example
spec:
  enabled: true
  workers: 10
