apiVersion: strata.ctx.sh/v1beta1
kind: Discovery
metadata:
  name: example-all
  namespace: default
spec:
  collector:
    - name: example
      namespace: default
---
apiVersion: strata.ctx.sh/v1beta1
kind: Discovery
metadata:
  name: example-app
  namespace: default
spec:
  resources:
    pods: true
    services: false
    endpoints: false
  selector:
    matchLabels:
      app: example
  collector:
    - name: example
      namespace: default
---
apiVersion: strata.ctx.sh/v1beta1
kind: Collector
metadata:
  name: example
  namespace: default
  labels:
    sink: example
spec:
  enabled: true
  workers: 2
  filters:
    clip:
      min: 0
      max: 5000
