apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
 - ../../base
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: strata-collector
      namespace: strata-collector
  - path: foo.yaml
    target:
      kind: ValidatingWebhookConfiguration
  - path: bar.yaml
    target:
      kind: MutatingWebhookConfiguration

secretGenerator:
  - name: strata-ctx-sh-webhook-tls
    namespace: strata-collector
    files:
      - tls.crt
      - tls.key
    type: kubernetes.io/tls

generatorOptions:
  disableNameSuffixHash: true

