apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
 - ../../base
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: strata-collector
      namespace: strata-collector
  # - service.yaml

generatorOptions:
  disableNameSuffixHash: true

