// Copyright 2023 Rob Lyon <rob@ctxswitch.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "ctx.sh/strata-collector/pkg/apis/strata.ctx.sh/v1beta1"
	scheme "ctx.sh/strata-collector/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DiscoveriesGetter has a method to return a DiscoveryInterface.
// A group's client should implement this interface.
type DiscoveriesGetter interface {
	Discoveries(namespace string) DiscoveryInterface
}

// DiscoveryInterface has methods to work with Discovery resources.
type DiscoveryInterface interface {
	Create(ctx context.Context, discovery *v1beta1.Discovery, opts v1.CreateOptions) (*v1beta1.Discovery, error)
	Update(ctx context.Context, discovery *v1beta1.Discovery, opts v1.UpdateOptions) (*v1beta1.Discovery, error)
	UpdateStatus(ctx context.Context, discovery *v1beta1.Discovery, opts v1.UpdateOptions) (*v1beta1.Discovery, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Discovery, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.DiscoveryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Discovery, err error)
	DiscoveryExpansion
}

// discoveries implements DiscoveryInterface
type discoveries struct {
	client rest.Interface
	ns     string
}

// newDiscoveries returns a Discoveries
func newDiscoveries(c *StrataV1beta1Client, namespace string) *discoveries {
	return &discoveries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the discovery, and returns the corresponding discovery object, and an error if there is any.
func (c *discoveries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Discovery, err error) {
	result = &v1beta1.Discovery{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("discoveries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Discoveries that match those selectors.
func (c *discoveries) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.DiscoveryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.DiscoveryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("discoveries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested discoveries.
func (c *discoveries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("discoveries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a discovery and creates it.  Returns the server's representation of the discovery, and an error, if there is any.
func (c *discoveries) Create(ctx context.Context, discovery *v1beta1.Discovery, opts v1.CreateOptions) (result *v1beta1.Discovery, err error) {
	result = &v1beta1.Discovery{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("discoveries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(discovery).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a discovery and updates it. Returns the server's representation of the discovery, and an error, if there is any.
func (c *discoveries) Update(ctx context.Context, discovery *v1beta1.Discovery, opts v1.UpdateOptions) (result *v1beta1.Discovery, err error) {
	result = &v1beta1.Discovery{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("discoveries").
		Name(discovery.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(discovery).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *discoveries) UpdateStatus(ctx context.Context, discovery *v1beta1.Discovery, opts v1.UpdateOptions) (result *v1beta1.Discovery, err error) {
	result = &v1beta1.Discovery{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("discoveries").
		Name(discovery.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(discovery).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the discovery and deletes it. Returns an error if one occurs.
func (c *discoveries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("discoveries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *discoveries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("discoveries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched discovery.
func (c *discoveries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Discovery, err error) {
	result = &v1beta1.Discovery{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("discoveries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
